# Example of power series expansion

In [31]:
# import modules
import pandas as pd
import numpy as np

1. Inter-industry transactions

In [32]:
Z = np.array([
    [0.6,2.6,0.5],
    [0.8, 30.6, 7.8],
    [0.9,12.1,23]])

Z

array([[ 0.6,  2.6,  0.5],
       [ 0.8, 30.6,  7.8],
       [ 0.9, 12.1, 23. ]])

2. Value added vector

In [33]:
# Value added (last row of the first table)
v = np.array([3.30, 22.4, 52.5])
v

array([ 3.3, 22.4, 52.5])

3. Final demand vector of products purchased by final consumers

In [34]:
y = np.array([1.9, 28.5, 47.8])
y

array([ 1.9, 28.5, 47.8])

In [35]:
x = Z.sum(1) + y
A = Z @ np.diag(1/x)
A

array([[0.10714286, 0.03840473, 0.00596659],
       [0.14285714, 0.45199409, 0.09307876],
       [0.16071429, 0.17872969, 0.27446301]])

In [36]:
L = np.linalg.inv(np.eye(A.shape[0])-A)
L

array([[1.1374997 , 0.08638219, 0.02043636],
       [0.35414416, 1.93137726, 0.25068774],
       [0.33920879, 0.49491248, 1.44457108]])

The Leontief as a power series expansion

$\mathbf{L} = \mathbf{I} + \mathbf{A} + \mathbf{A}^{2} + \mathbf{A}^{3} + ... + \mathbf{A}^{n}$

In [43]:
def leontief_inverse_power_series(A, n_terms):
    """
    Compute the Leontief inverse using power series expansion.

    Args:
    A: numpy array or pandas dataframe, the input-output matrix.
    n_terms: int, the number of terms in the power series expansion.

    Returns:
    L_approximate: numpy array, the Leontief inverse approximation.
    """
    I = np.eye(A.shape[0])
    L_approximate = I.copy()
    A_power = I.copy()
    
    for i in range(n_terms):
        A_power = A_power @ A
        L_approximate += A_power

    return L_approximate

In [44]:
leontief_inverse_power_series(A, 30),L

(array([[1.1374997 , 0.08638219, 0.02043636],
        [0.35414415, 1.93137726, 0.25068774],
        [0.33920879, 0.49491247, 1.44457108]]),
 array([[1.1374997 , 0.08638219, 0.02043636],
        [0.35414416, 1.93137726, 0.25068774],
        [0.33920879, 0.49491248, 1.44457108]]))