# Practical 1: Basics of IOA

In [11]:
# Import packages
import numpy as np

## Recreate a 3x3 IO system using numpy and calculate the total product output and total product input

#### Interindustry Transaction Table

| Z (Unit: Trillion €/year)  | Agriculture | Industry | Service |
|----------------------------|-------------|----------|---------|
| Agriculture                | 0.6         | 2.6      | 0.5     |
| Industry                   | 0.8         | 30.6     | 7.8     |
| Service                    | 0.9         | 12.1     | 23.0    |

In [21]:
# interindustry transaction table
Z = np.array([[0.6,2.6,0.5],[0.8,30.6,7.8],[0.9,12.1,23.0]])
Z

array([[ 0.6,  2.6,  0.5],
       [ 0.8, 30.6,  7.8],
       [ 0.9, 12.1, 23. ]])

#### Final Demand

| Y (Unit: Trillion €/year)| Domestic | Export   |
|--------------------------|----------|----------|
| Agriculture              | 1.9      | 0        |
| Industry                 | 28.5     | 0        |
| Service                  | 47.8     | 0        |

In [26]:
Y = np.array([[1.9,0],[28.5,0],[47.8,0]])
Y

array([[ 1.9,  0. ],
       [28.5,  0. ],
       [47.8,  0. ]])

#### Value Added

| V (Unit: Trillion €/year)  | Agriculture | Industry | Service |
|----------------------------|-------------|----------|---------|
| Value Added                | 3.3         | 22.3     | 52.5    |

In [27]:
V = np.array([3.3,22.3,52.5])
V

array([ 3.3, 22.3, 52.5])

### Calculate the total product output $\mathbf{x}$

$\mathbf{x}=\displaystyle\sum_{j=1}^{n} Z_{ij} + \sum_{j=1}^{n} Y_{ij}$

In [28]:
x = Z.sum(1) + Y.sum(1)
x

array([ 5.6, 67.7, 83.8])

### Calculate the total product input $\mathbf{x}'$

$\mathbf{x}'=\displaystyle\sum_{i=1}^{m} Z_{ij} + \sum_{i=1}^{m} V_{ij}$

In [29]:
x_ = Z.sum(0) + V
x_

array([ 5.6, 67.6, 83.8])