In [7]:
import numpy as np

In [2]:
### Question 1.a
result = 3 / 5
print(f"Result: {result} with type {type(result)}")

Result: 0.6 with type <class 'float'>


In [3]:
result = 3 * 5
print(f"Result: {result} with type {type(result)}")

Result: 15 with type <class 'int'>


In [19]:
### Question 1.b
result = 4.5 * 5
print(f"Result: {result} with type {type(result)}")

Result: 22.5 with type <class 'float'>


In [4]:
### Question 1.c
value_list = [3, 4, 5, 7.3]
result = sum(value_list)
print(f"Result: {result} ")

Result: 19.3 


In [5]:
### Question 1.d
# List indexes in python start from 0, so the second item is at index 1.
second_item = value_list[1]
print(f"Second item 4 is equal to second item: {second_item == 4}")

Second item 4 is equal to second item: True


In [8]:
### Question 2.a
integer_list = [1, 2, 3, 4, 5, 5, 7, 34567, 7754]
array_one = np.array(integer_list)
array_one

array([    1,     2,     3,     4,     5,     5,     7, 34567,  7754])

In [9]:
### Question 2.b
array_one + 3

array([    4,     5,     6,     7,     8,     8,    10, 34570,  7757])

In [10]:
### Question 2.b
array_one / 5

array([2.0000e-01, 4.0000e-01, 6.0000e-01, 8.0000e-01, 1.0000e+00,
       1.0000e+00, 1.4000e+00, 6.9134e+03, 1.5508e+03])

In [15]:
### Question 2.c
# You can create an array from a list of lists
array_two = np.array([
    [2, 6.7, 8],
    [4, 3.14, 24]
])
print(f"Array two looks like:\n{array_two}\nand its shape is {array_two.shape}")

Array two looks like:
[[ 2.    6.7   8.  ]
 [ 4.    3.14 24.  ]]
and its shape is (2, 3)


(2, 3)

In [16]:
### Question 2.d
# np.sum(array_two) or array_two.sum(): both return the sum of all values in the array.
array_two.sum()

47.84

In [17]:
### Question 2.e
# We can sum over an axis of the array, axis 0 are the rows, axis 1 are the columns.
# To find the sum of the rows, we collapse axis 1 (the columns)
array_two.sum(axis=1)

array([16.7 , 31.14])

In [18]:
### Question 2.f
array_two.sum(axis=1, keepdims=True)

array([[16.7 ],
       [31.14]])